#
# 特に説明の無いファイルパスは Profile フォルダーからの相対パスです。
#

[Engine]

# 将棋ソフトの表示名です。 後ろにバージョン番号が付くなどの加工があることがあります。
# 開発中の仮称 "Kifuwarabe ShogiAgarutha", "Kifuwarabe Dobutu9x9"
# 出場時 "Kifuwarabe SDT5"
Name = "Kifuwarabi"

# 将棋ソフトの制作者名です。
Author = "Satoshi TAKAHASHI"

[Resources]

Command = "./Command"
LogDirectory = "../Logs"
